# Generated by Django 2.2.27 on 2022-06-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
