# Generated by Django 4.1.7 on 2023-06-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_email_userprofile_name'),
        ('product', '0018_alter_category_id_alter_comment_id_alter_images_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
            preserve_default=False,
        ),
    ]
