# Generated by Django 4.0.4 on 2022-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adminnote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
